/*
 * NiFi Rest API
 * The Rest API provides programmatic access to command and control a NiFi instance in real time. Start and                                             stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * OpenAPI spec version: 1.15.1
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.github.akhil11101997.nifi.client.api;

import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AccesssamlApi
 */
@Ignore
public class AccesssamlApiTest {

    private final AccesssamlApi api = new AccesssamlApi();

    
    /**
     * Local logout when SAML is enabled, does not communicate with the IDP.
     *
     * Note: This endpoint is subject to change as NiFi and it&#39;s REST API evolve.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void samlLocalLogoutTest() throws Exception {
        api.samlLocalLogout();

        // TODO: test validations
    }
    
    /**
     * Retrieves a JWT following a successful login sequence using the configured SAML identity provider.
     *
     * Note: This endpoint is subject to change as NiFi and it&#39;s REST API evolve.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void samlLoginExchangeTest() throws Exception {
        String response = api.samlLoginExchange();

        // TODO: test validations
    }
    
    /**
     * Processes the SSO response from the SAML identity provider for HTTP-POST binding.
     *
     * Note: This endpoint is subject to change as NiFi and it&#39;s REST API evolve.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void samlLoginHttpPostConsumerTest() throws Exception {
        api.samlLoginHttpPostConsumer();

        // TODO: test validations
    }
    
    /**
     * Processes the SSO response from the SAML identity provider for HTTP-REDIRECT binding.
     *
     * Note: This endpoint is subject to change as NiFi and it&#39;s REST API evolve.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void samlLoginHttpRedirectConsumerTest() throws Exception {
        api.samlLoginHttpRedirectConsumer();

        // TODO: test validations
    }
    
    /**
     * Initiates an SSO request to the configured SAML identity provider.
     *
     * Note: This endpoint is subject to change as NiFi and it&#39;s REST API evolve.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void samlLoginRequestTest() throws Exception {
        api.samlLoginRequest();

        // TODO: test validations
    }
    
    /**
     * Retrieves the service provider metadata.
     *
     * Note: This endpoint is subject to change as NiFi and it&#39;s REST API evolve.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void samlMetadataTest() throws Exception {
        api.samlMetadata();

        // TODO: test validations
    }
    
    /**
     * Processes a SingleLogout message from the configured SAML identity provider using the HTTP-POST binding.
     *
     * Note: This endpoint is subject to change as NiFi and it&#39;s REST API evolve.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void samlSingleLogoutHttpPostConsumerTest() throws Exception {
        api.samlSingleLogoutHttpPostConsumer();

        // TODO: test validations
    }
    
    /**
     * Processes a SingleLogout message from the configured SAML identity provider using the HTTP-REDIRECT binding.
     *
     * Note: This endpoint is subject to change as NiFi and it&#39;s REST API evolve.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void samlSingleLogoutHttpRedirectConsumerTest() throws Exception {
        api.samlSingleLogoutHttpRedirectConsumer();

        // TODO: test validations
    }
    
    /**
     * Initiates a logout request using the SingleLogout service of the configured SAML identity provider.
     *
     * Note: This endpoint is subject to change as NiFi and it&#39;s REST API evolve.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void samlSingleLogoutRequestTest() throws Exception {
        api.samlSingleLogoutRequest();

        // TODO: test validations
    }
    
}
